name: 'Run an action based on version'

runs:
  using: composite
  steps:
    - name: Echo the version of Platform Repo
      shell: bash
      run: |
        echo "This is version ${{ github.action_ref }}"
        
    - name: List all files in calling repository V2.0
      shell: bash
      run: |
        echo "This action is a newer version: VERSION 2.0"
        echo "=== Files in calling repository ==="
        echo "Current directory: $(pwd)"
        echo "Contents of ./project-code/:"
        find ./project-code/ -type f -not -path './.git/*' | sort
        
    - name: Show project structure
      shell: bash
      run: |
        echo "=== Project directory structure ==="
        if [ -d "./project-code" ]; then
          cd ./project-code
          echo "Files in project repository:"
          ls -la
        else
          echo "Warning: ./project-code/ directory not found"
          echo "Available directories:"
          ls -la
        fi