name: Build App

on:
  workflow_call:
    inputs:
      platform-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4
      - name: Use versioned platform action
        uses: asharma54-wiq/Demo-Platform-Repo/.github/actions/versioned-action@${{ inputs.platform-version }}
      