name: Build App

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository, This is v1.0
        uses: actions/checkout@v4
        with:
          path: './project-code'
          
      - name: Use platform action locally, This is v1.0
        uses: ./platform-code/.github/actions/versioned-action