name: Build App

on:
  workflow_call:
    inputs:
      platform-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          path: './project-code'
          
      - name: Checkout platform repository
        uses: actions/checkout@v4
        with:
          repository: asharma54-wiq/Demo-Platform-Repo
          ref: ${{ inputs.platform-version }}
          path: './platform-code'
          
      - name: Use platform action locally
        uses: ./platform-code/.github/actions/versioned-action