name: Build App

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository, This is v2.0
        uses: actions/checkout@v4
        with:
          path: './project-code'

      - name: Echo the version, This is v2.0
        shell: bash
        run: |
          echo 'This is version 2.0 of the workflow'
          
      - name: Use platform action locally, This is v2.0
        uses: asharma54-wiq/Demo-Platform-Repo/.github/actions/versioned-action@v2.0